# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43cdae0e90a4ed311c77cdc7add44bd50b1b3145eb395bdb460a8355d18cc6d706cff21ecef9a0e698b39ea22d59c53ced079ccc559aeea92145049514f31a71

test:
  secret_key_base: f42a3ab557cff3fcfd1a6b0121544ebad8f431834b02f3c0b2febb033ad19f3b07bed3ba68ff2b62794e7aa53eed322b7a4e430e87ee408511e1fd27d8a703f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
